// Code generated by "stringer -type=Suit,Rank"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[spade-0]
	_ = x[diamond-1]
	_ = x[club-2]
	_ = x[heart-3]
	_ = x[joker-4]
}

const _Suit_name = "spadediamondclubheartjoker"

var _Suit_index = [...]uint8{0, 5, 12, 16, 21, 26}

func (i Suit) String() string {
	if i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ace-1]
	_ = x[two-2]
	_ = x[three-3]
	_ = x[four-4]
	_ = x[five-5]
	_ = x[six-6]
	_ = x[seven-7]
	_ = x[eight-8]
	_ = x[nine-9]
	_ = x[ten-10]
	_ = x[jack-11]
	_ = x[queen-12]
	_ = x[king-13]
}

const _Rank_name = "acetwothreefourfivesixseveneightninetenjackqueenking"

var _Rank_index = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 32, 36, 39, 43, 48, 52}

func (i Rank) String() string {
	i -= 1
	if i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
